### ISSUE TITLE
Can't seem to set margins

### ISSUE THREAD

**Issue by hoffmang9** [fifsky/html-to-pdf-action#2]
I'm attempting to convert an html doc and all of the margin parameters I've tried seem to have no effect. Is there potentially a way to set a higher verbosity or some other way to debug?

Run: https://github.com/Chia-Network/chiapos/runs/942236433?check_suite_focus=true
Action: https://github.com/Chia-Network/chiapos/blob/build-pdf/.github/workflows/doc-html-pdf.yml

Thanks in advance for any assistance.

**Comment by fifsky** [comment]
I tried to fix it. You can try again

**Comment by hoffmang9** [comment]
Good news and bad news.

The good - margins are now working as they're supposed to.
The bad - font selection/style sheet choice somehow changed.

[Now with correct 1cm margins](https://github.com/fifsky/html-to-pdf-action/files/5020113/proof_of_space.pdf)
[Correct typeset from before with no margins](https://github.com/fifsky/html-to-pdf-action/files/5020114/proof_of_space.2.pdf)

Let me look through your changes and see if I can spot the issue too.

**Comment by hoffmang9** [comment]
Looks like it's this font install overriding?
https://github.com/fifsky/html-to-pdf-action/compare/v0.0.2...bb2c180b29cdedc92a94763d22e39a08ce6a5cee#diff-3254677a7917c6c01f55212f86c57fbfR7

**Comment by fifsky** [comment]
Font is installed because I need to display Chinese, I will remove the font first, you try again

**Comment by hoffmang9** [comment]
That fixed the font/display issue. Thank you!

https://github.com/Chia-Network/chiapos/runs/943422424?check_suite_focus=true
